name: smartpub
description: Smart Flutter dependency analyzer that cleans and organizes pubspec.yaml by detecting unused, misplaced, and duplicate dependencies.
version: 1.0.3
homepage: https://github.com/VatsalJaganwala/smartpub
repository: https://github.com/VatsalJaganwala/smartpub
issue_tracker: https://github.com/VatsalJaganwala/smartpub/issues
documentation: https://github.com/VatsalJaganwala/smartpub

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  # Color Picker & Utilities
  ansicolor: ^2.0.2

  # Command Line (CLI) or Console
  args: ^2.4.2

  # File, Folder & Path Utilities
  path: ^1.8.3

  # HTTP Client & Utilities
  http: ^1.1.2

  # XML, YAML & Interchange Formats
  yaml: ^3.1.2
  pub_semver: ^2.2.0
dev_dependencies:
  # Testing
  test: ^1.24.9

  # Linter
  flutter_lints: ^6.0.0
executables:
  smartpub: smartpub

platforms:
  linux:
  macos:
  windows:

topics:
  - dependencies
  - pubspec
  - analyzer
  - cli
  - developer-tools
